name: test

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: ["13.4"]

    steps:
      - name: Switch Xcode
        run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Print Xcode version
        run: xcodebuild -version
      - uses: actions/checkout@v3
      - name: Build IndexStore
        run: ./.github/build-index-store.sh
      - name: Build index-import
        run: ./.github/build-index-import.sh
      - name: Test
        run: ./tests/run.sh
